api_platform:
    title: 'ElKarmeletAPI'
    description: 'ElKarmelet API'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']


    formats:
        json:
            mime_types: [ 'application/json' ]
        html:
            mime_types: ['text/html']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    metadata_backward_compatibility_layer: false
